DROP TABLE answers
IF EXISTS;
DROP TABLE questionnaires
IF EXISTS;
DROP TABLE surveys
IF EXISTS;
DROP SEQUENCE SURVEY_SEQ
IF EXISTS;

DROP TABLE answervars
IF EXISTS;
DROP TABLE questionvars
IF EXISTS;
DROP TABLE questionkits
IF EXISTS;
DROP TABLE answerkits
IF EXISTS;
DROP SEQUENCE CONSTRUCTOR_SEQ
IF EXISTS;


DROP TABLE persons
IF EXISTS;
DROP TABLE groups
IF EXISTS;
DROP TABLE department
IF EXISTS;
DROP SEQUENCE GLOBAL_SEQ
IF EXISTS;