CREATE SEQUENCE IF NOT EXISTS SURVEY_SEQ
  AS INTEGER
    START WITH 1000;


CREATE TABLE IF NOT EXISTS surveys
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE SURVEY_SEQ  PRIMARY KEY,
  name          VARCHAR(255),
  comment       VARCHAR(1000),
  createDate    DATE NOT NULL,
  questionKitId INTEGER,
  department    VARCHAR(255),
  groupName     VARCHAR(255)


);


CREATE TABLE IF NOT EXISTS questionnaires
(
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE SURVEY_SEQ  PRIMARY KEY,
  number     INTEGER,
  createDate DATE NOT NULL,
  survey_id  INTEGER,

  FOREIGN KEY (survey_id) REFERENCES surveys (id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions
(
  id                 INTEGER GENERATED BY DEFAULT AS SEQUENCE SURVEY_SEQ  PRIMARY KEY,
  number             INTEGER,
  name               VARCHAR(255),
  questionVarId      INTEGER,
  superQuestionVarId INTEGER,
  survey_id          INTEGER,
  FOREIGN KEY (survey_id) REFERENCES surveys (id)
    ON DELETE CASCADE

);


CREATE TABLE IF NOT EXISTS answers
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE SURVEY_SEQ  PRIMARY KEY,
  name             VARCHAR(255),
  questionnaire_id INTEGER,
  question_id      INTEGER,

  FOREIGN KEY (questionnaire_id) REFERENCES questionnaires (id)
    ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES questions (id)
    ON DELETE CASCADE
);